import sys, os
from Bio import SeqIO

files = []
dict_cluster = {}
dict_cds = {}

"""
inside the output directory generated by Antismash5

usage : for i in *.region*; do python get_geneclusters.py ${i} ; done
"""

in_dir = sys.argv[1]
path = os.path.realpath(in_dir)
out_name = in_dir + ".geneclusters.txt"
out_file = open(out_name, "w")


for i in os.listdir(in_dir):

	if ".region" in i:

		f = os.path.join(in_dir, i)

		files.append(f)

for f in files:

	region = f.split('/')[-1].split('.')[2]

	for record in SeqIO.parse(f, "genbank"):

		for feature in record.features:

			if feature.type == "protocluster":

				locus_tag = feature.qualifiers.get("protocluster_number", ["???"])[0]
				product = feature.qualifiers.get("product", ["???"])[0]

				if record.id not in dict_cluster:

					dict_cluster[record.id, record.description, region] = [product]

				else:

					dict_cluster[record.id, record.description, region].append(product)

	for record in SeqIO.parse(f, "genbank"):

		cds = []

		for feature in record.features:

			if feature.type == "CDS":

				cds.append(feature.qualifiers.get("protein_id", [""])[0])

				protein_id = feature.qualifiers.get("protein_id", "???")[0]

		if record.id not in dict_cds:

			dict_cds[record.id, record.description, region] = cds

for k, v in sorted(dict_cluster.iteritems()):

	out_file.write(  '\t'.join(k) + '\t' +  "".join(v) + '\t' + ",".join(dict_cds[k])  + '\n') 

out_file.close()
